const extToLang: Record<string, string> = {
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  ts: "typescript",
  mts: "typescript",
  cts: "typescript",
  tsx: "tsx",
  jsx: "jsx",
  json: "json",
  yaml: "yaml",
  yml: "yaml",
  toml: "toml",
  xml: "xml",
  html: "html",
  htm: "html",
  css: "css",
  scss: "scss",
  less: "less",
  md: "markdown",
  mdx: "mdx",
  py: "python",
  rb: "ruby",
  go: "go",
  rs: "rust",
  c: "c",
  h: "c",
  cpp: "cpp",
  hpp: "cpp",
  java: "java",
  kt: "kotlin",
  swift: "swift",
  sh: "shellscript",
  bash: "shellscript",
  zsh: "shellscript",
  fish: "fish",
  sql: "sql",
  graphql: "graphql",
  gql: "graphql",
  lua: "lua",
  r: "r",
  pl: "perl",
  php: "php",
  tf: "hcl",
  ini: "ini",
  conf: "ini",
  cfg: "ini",
  env: "dotenv",
  csv: "csv",
  diff: "diff",
  patch: "diff",
  makefile: "makefile",
};

const nameToLang: Record<string, string> = {
  Dockerfile: "dockerfile",
  Containerfile: "dockerfile",
  Makefile: "makefile",
  Gemfile: "ruby",
  Rakefile: "ruby",
  Vagrantfile: "ruby",
  Jenkinsfile: "groovy",
  ".gitignore": "gitignore",
  ".dockerignore": "gitignore",
  ".env": "dotenv",
  ".bashrc": "shellscript",
  ".zshrc": "shellscript",
  ".profile": "shellscript",
  "nginx.conf": "nginx",
  "tsconfig.json": "jsonc",
};

export function detectLanguage(filePath: string): string | undefined {
  const name = filePath.split("/").pop() ?? "";
  if (nameToLang[name]) return nameToLang[name];
  const ext = name.includes(".") ? name.split(".").pop()?.toLowerCase() : undefined;
  if (ext && extToLang[ext]) return extToLang[ext];
  return undefined;
}
